# Generated by Django 3.0.4 on 2020-05-25 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Matching_Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_name', models.CharField(max_length=20)),
                ('new_leftBV', models.IntegerField(default=0)),
                ('new_rightBV', models.IntegerField(default=0)),
                ('match_BV', models.CharField(default='0:0', max_length=50)),
                ('matching_income', models.IntegerField(default=0)),
                ('carry_leftBV', models.IntegerField(default=0)),
                ('carry_rightBV', models.IntegerField(default=0)),
                ('total_leftBV', models.IntegerField(default=0)),
                ('total_rightBV', models.IntegerField(default=0)),
                ('collapse_leftBV', models.IntegerField(default=0)),
                ('collapse_rightBV', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Matching_Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_name', models.CharField(max_length=20)),
                ('new_leftBV', models.IntegerField(default=0)),
                ('new_rightBV', models.IntegerField(default=0)),
                ('match_BV', models.CharField(default='0:0', max_length=50)),
                ('matching_income', models.IntegerField(default=0)),
                ('carry_leftBV', models.IntegerField(default=0)),
                ('carry_rightBV', models.IntegerField(default=0)),
                ('total_leftBV', models.IntegerField(default=0)),
                ('total_rightBV', models.IntegerField(default=0)),
                ('collapse_leftBV', models.IntegerField(default=0)),
                ('collapse_rightBV', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Requested_Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('date', models.DateField(default='1999-01-01')),
                ('fund', models.IntegerField(default=0)),
                ('transection_no', models.IntegerField(default=0)),
                ('proof', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('status', models.CharField(default='Pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Show_ROI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_date', models.DateField(auto_now_add=True, null=True)),
                ('user_name', models.CharField(default='', max_length=30)),
                ('roi_income', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tree_View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('left', models.CharField(default='null', max_length=50)),
                ('right', models.CharField(default='null', max_length=50)),
                ('left_count', models.IntegerField(default=0)),
                ('right_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Update_ROI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('roi_income', models.IntegerField(default=0)),
                ('starting_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('activated_amount', models.IntegerField(default=0)),
                ('ending_date', models.DateField(default='1920-05-01')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Roi_Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_Rincome', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ROI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=20)),
                ('date', models.DateField(default='1999-01-01')),
                ('income', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phon_no', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=50)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('package', models.IntegerField(default=1000)),
                ('is_active', models.BooleanField(default=False)),
                ('active_amount', models.IntegerField(default=0)),
                ('sponsor_id', models.CharField(default='null', max_length=50)),
                ('side', models.CharField(default='null', max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avail_fund', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DirectSponsor_Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_date', models.DateField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=30)),
                ('activated_amount', models.IntegerField(default=0)),
                ('direct_income', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Direct_Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_Dincome', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Binary_Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_Bincome', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
