# Generated by Django 3.0.4 on 2020-05-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='binary_wallet',
            old_name='total_Bincome',
            new_name='b_income',
        ),
        migrations.RenameField(
            model_name='direct_wallet',
            old_name='total_Dincome',
            new_name='d_income',
        ),
        migrations.RenameField(
            model_name='roi_wallet',
            old_name='total_Rincome',
            new_name='r_income',
        ),
        migrations.AddField(
            model_name='binary_wallet',
            name='total_bincome',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='direct_wallet',
            name='total_dincome',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roi_wallet',
            name='total_rincome',
            field=models.IntegerField(default=0),
        ),
    ]
