# Generated by Django 3.0.4 on 2020-05-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_amount',
            field=models.IntegerField(default=0),
        ),
    ]
