# Generated by Django 3.0.4 on 2020-05-29 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_app', '0003_auto_20200526_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(default='-', max_length=40)),
                ('account_number', models.CharField(default='-', max_length=30)),
                ('branch_name', models.CharField(default='-', max_length=40)),
                ('ifsc_code', models.CharField(default='-', max_length=20)),
                ('bank_name', models.CharField(default='-', max_length=30)),
                ('nominee_name', models.CharField(default='-', max_length=30)),
                ('aadhar_number', models.CharField(default='-', max_length=12)),
                ('pan_number', models.CharField(default='-', max_length=10)),
                ('aadhar_image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('pan_image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('p_image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
