# Generated by Django 3.0.4 on 2020-05-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_bank_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_info',
            name='cheak',
            field=models.BooleanField(default=False),
        ),
    ]
